name: Dev Deployer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Application Deployer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: ./fe-deployer.sh
